// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoPdFzzcv5Xan6ptczl16PcpKPPpUjkM',
    appId: '1:870771565062:web:1cf4b2c039ba6fc44b5987',
    messagingSenderId: '870771565062',
    projectId: 'ff-cli-test-20240510',
    authDomain: 'ff-cli-test-20240510.firebaseapp.com',
    storageBucket: 'ff-cli-test-20240510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2_oBxebrxWnWxmBoYu1AMa0C0kcHBPA',
    appId: '1:870771565062:android:64ed12b402353a874b5987',
    messagingSenderId: '870771565062',
    projectId: 'ff-cli-test-20240510',
    storageBucket: 'ff-cli-test-20240510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkx_wg_O6wod4JHRKSR43JOHR4Lqglh0',
    appId: '1:870771565062:ios:ebb9f0aeda503b514b5987',
    messagingSenderId: '870771565062',
    projectId: 'ff-cli-test-20240510',
    storageBucket: 'ff-cli-test-20240510.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSkx_wg_O6wod4JHRKSR43JOHR4Lqglh0',
    appId: '1:870771565062:ios:ebb9f0aeda503b514b5987',
    messagingSenderId: '870771565062',
    projectId: 'ff-cli-test-20240510',
    storageBucket: 'ff-cli-test-20240510.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtoPdFzzcv5Xan6ptczl16PcpKPPpUjkM',
    appId: '1:870771565062:web:4aa685234901c5334b5987',
    messagingSenderId: '870771565062',
    projectId: 'ff-cli-test-20240510',
    authDomain: 'ff-cli-test-20240510.firebaseapp.com',
    storageBucket: 'ff-cli-test-20240510.appspot.com',
  );
}
