// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpTyHHXkjaQ9fPDrUihMT-_BkKbfBHlI',
    appId: '1:1048971246583:web:530179613b94c0145a0cf2',
    messagingSenderId: '1048971246583',
    projectId: 'calendar-scheduler-b05de',
    authDomain: 'calendar-scheduler-b05de.firebaseapp.com',
    storageBucket: 'calendar-scheduler-b05de.appspot.com',
    measurementId: 'G-L0G2TG4WFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0ayy71PwLcduSwdUc5FAzcqy-_1-xW4',
    appId: '1:1048971246583:android:6835cd0933c65e705a0cf2',
    messagingSenderId: '1048971246583',
    projectId: 'calendar-scheduler-b05de',
    storageBucket: 'calendar-scheduler-b05de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0aoiYqUGcHXj4QL4g4QfdL7MeqCvJM4g',
    appId: '1:1048971246583:ios:a13038a3111411855a0cf2',
    messagingSenderId: '1048971246583',
    projectId: 'calendar-scheduler-b05de',
    storageBucket: 'calendar-scheduler-b05de.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0aoiYqUGcHXj4QL4g4QfdL7MeqCvJM4g',
    appId: '1:1048971246583:ios:a13038a3111411855a0cf2',
    messagingSenderId: '1048971246583',
    projectId: 'calendar-scheduler-b05de',
    storageBucket: 'calendar-scheduler-b05de.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVpTyHHXkjaQ9fPDrUihMT-_BkKbfBHlI',
    appId: '1:1048971246583:web:d7633ba4c32a21265a0cf2',
    messagingSenderId: '1048971246583',
    projectId: 'calendar-scheduler-b05de',
    authDomain: 'calendar-scheduler-b05de.firebaseapp.com',
    storageBucket: 'calendar-scheduler-b05de.appspot.com',
    measurementId: 'G-FL7YM2MZ7P',
  );
}
